plugins { id 'net.fabricmc.fabric-loom' version "${loom_version}"; id 'maven-publish' }
loom { splitEnvironmentSourceSets(); mods { "voxy_next" { sourceSet sourceSets.main; sourceSet sourceSets.client } } }
dependencies { minecraft "com.mojang:minecraft:${minecraft_version}"; implementation "net.fabricmc:fabric-loader:${loader_version}"; implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}" }
sourceSets.main.java.srcDirs += ['../common/src/main/java']
sourceSets.main.resources.srcDirs += ['../common/src/main/resources']
def generatedVersion = project.version.toString()
processResources {
    inputs.property 'version', generatedVersion
    filesMatching('fabric.mod.json') { expand(version: generatedVersion) }
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }
java { withSourcesJar(); sourceCompatibility = JavaVersion.VERSION_25; targetCompatibility = JavaVersion.VERSION_25 }
jar { from('../LICENSE') { rename { 'LICENSE_VoxyNext' } } }
base { archivesName = mod_id }