plugins { id 'java-library'; id 'net.neoforged.moddev' version '2.0.148'; id 'idea' }
version=mod_version; group=mod_group_id; base { archivesName=mod_id }; java.toolchain.languageVersion=JavaLanguageVersion.of(25)
sourceSets.main.java.srcDirs += ['../common/src/main/java']; sourceSets.main.resources.srcDirs += ['../common/src/main/resources']
neoForge { version=project.neo_version; runs { client { client() }; server { server(); programArgument '--nogui' } }; mods { "voxy_next" { sourceSet sourceSets.main } } }
var generateModMetadata=tasks.register('generateModMetadata',ProcessResources){ var replaceProperties=[minecraft_version:minecraft_version,minecraft_version_range:minecraft_version_range,neo_version:neo_version,mod_id:mod_id,mod_name:mod_name,mod_license:mod_license,mod_version:mod_version]; inputs.properties replaceProperties; expand replaceProperties; from 'src/main/templates'; into 'build/generated/sources/modMetadata' }
sourceSets.main.resources.srcDir generateModMetadata; neoForge.ideSyncTask generateModMetadata