org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.52-beta
mod_id=voxy_next
mod_name=Voxy Next
mod_license=MIT
mod_version=0.1.0-alpha
mod_group_id=com.zhirkovtag.voxynext
